/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cmt_octopus_RwlAdapter */

#ifndef _Included_com_cmt_octopus_RwlAdapter
#define _Included_com_cmt_octopus_RwlAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    InitComm
 * Signature: (III)Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_InitComm
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    TxnAmt
 * Signature: (IICC)Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_TxnAmt
  (JNIEnv *, jobject, jint, jint, jchar, jchar);

/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    TimeVer
 * Signature: ()Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_TimeVer
  (JNIEnv *, jobject);

/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    Poll
 * Signature: (CC)Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_Poll
  (JNIEnv *, jobject, jchar, jchar);

/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    PollEx
 * Signature: (CC)Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_PollEx
  (JNIEnv *, jobject, jchar, jchar);

/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    Deduct
 * Signature: (IIII)Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_Deduct
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    XFile
 * Signature: ()Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_XFile
  (JNIEnv *, jobject);

/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    Reset
 * Signature: ()Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_Reset
  (JNIEnv *, jobject);

/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    WriteID
 * Signature: (I)Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_WriteID
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    HouseKeeping
 * Signature: ()Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_HouseKeeping
  (JNIEnv *, jobject);

/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    PortClose
 * Signature: ()Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_PortClose
  (JNIEnv *, jobject);

/*
 * Class:     com_cmt_octopus_RwlAdapter
 * Method:    GetExtraInfo
 * Signature: (II)Lcom/cmt/octopus/RwlReturn;
 */
JNIEXPORT jobject JNICALL Java_com_cmt_octopus_RwlAdapter_GetExtraInfo
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
