/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cmt_util_gpio_GPIOCtrl */

#ifndef _Included_com_cmt_util_gpio_GPIOCtrl
#define _Included_com_cmt_util_gpio_GPIOCtrl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cmt_util_gpio_GPIOCtrl
 * Method:    GetPin
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_cmt_util_gpio_GPIOCtrl_GetPin
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
